### ISSUE TITLE
Excuse me, does 0.0.24 support a 3h testing network?

### ISSUE THREAD

**Issue by zsvvv** [nazar-pc/space-acres#106]
If not, when will the 3h supported version appear? I believe many people are waiting for your release

**Comment by nazar-pc** [comment]
It does not support 3h yet, 3h support will be added later.
3g is still the incentivized network, so you shouldn't be missing much for now.

Bit 3h support will be added before it becomes incentivized.

**Comment by zsvvv** [comment]
> It does not support 3h yet, 3h support will be added later. 3g is still the incentivized network, so you shouldn't be missing much for now.
> 
> Bit 3h support will be added before it becomes incentivized.

It is your ACRES that allows more people to participate, because for most people, CLI is very difficult, and you are right. Thank you.



I hope that in the future, ACRES can add the function of sharing nodes in the local area network. For example, computer A can synchronize nodes normally, and other computers in the local area network can fill in A's IP address to obtain nodes for farming



Thank you again
