### ISSUE TITLE
How do computers within the same LAN share a node? If it doesn't work now, will it be supported in the future? thanks

### ISSUE THREAD

**Issue by zsvvv** [nazar-pc/space-acres#111]

**Comment by nazar-pc** [comment]
Not supported right now, Space Acres combines node and farmer into one easy to use app.

If/when https://github.com/subspace/subspace/issues/2402 is implemented, Space Acres will support a similar feature too.

**Comment by zsvvv** [comment]
> 目前尚不支持，Space Acres 将节点和农夫结合到一个易于使用的应用程序中。
> 
> 如果/当[subspace/subspace#2402](https://github.com/subspace/subspace/issues/2402)被实现时，Space Acres 也将支持类似的功能。



Hope to achieve it soon, thank you
