### ISSUE TITLE
Clipping farm sectors in plot visualisation

### ISSUE THREAD

**Issue by jim-counter** [nazar-pc/space-acres#119]
There are some sectors not being displayed on the UI as per the screenshot below. Possibly just the last row is missing.

![image](https://github.com/nazar-pc/space-acres/assets/11335994/eef115f3-90ae-4134-8a78-cafa22c7ac58)

**Comment by nazar-pc** [comment]
It would help if you attach screenshot of the whole window. Looks like you just need to scroll down a bit.

**Comment by jim-counter** [comment]
![image](https://github.com/nazar-pc/space-acres/assets/11335994/b7046d4e-1a6f-4602-9267-cbcea3d0a74f)

Also suspicious that my second farm finishes exactly on the end of the row.

![image](https://github.com/nazar-pc/space-acres/assets/11335994/8eb49efb-8345-4e3b-84eb-7e731245bcd2)

**Comment by nazar-pc** [comment]
Yep, GTK definitely refuses to show the last row for some inexplicable reason :confused:

Reported to GTK as a comment here: https://gitlab.gnome.org/GNOME/gtk/-/issues/6360

Will try to rewrite this visualization in some other way to bypass the issue.

**Comment by nazar-pc** [comment]
This build should fix the issue and render useful information when hovering over sectors: https://github.com/nazar-pc/space-acres/actions/runs/7854968476
