### ISSUE TITLE
Benchmark results screen

### ISSUE THREAD

**Issue by jim-counter** [nazar-pc/space-acres#77]
Run benchmarks on configured plots on startup and provide that information in one of the about windows. Bonus if we can demonstrate the headroom something like this:

![image](https://github.com/nazar-pc/space-acres/assets/11335994/e742eddc-e838-4149-8b75-c9054bc964ec)

**Comment by nazar-pc** [comment]
I was thinking about something different: show in real time farming speed and give a visual indication (green/yellow/red) about the performance, such that farmer knows if they have fast enough machine and how often they failed to audit or didn't have enough time to prove the solution.

Would that be equivalent or not?

**Comment by jim-counter** [comment]
Yes, this sounds even better as it's based on the live results. I guess the overriding goal here is to know how close you are to the limits of your hardware.
