### ISSUE TITLE
About dual CPU system support

### ISSUE THREAD

**Issue by zsvvv** [nazar-pc/space-acres#97]
When a dual CPU system is in a farm, only one CPU is working and the occupancy rate is maintained at around 60%. It is not fully utilized, which affects efficiency. How to enable them to participate in the farm at the same time

**Comment by nazar-pc** [comment]
With two CPUs you need to have at least 2 farms to engage all cores. This is the same behavior as the default behavior in https://github.com/subspace/subspace

**Comment by zsvvv** [comment]
> 对于两个 CPU，您需要至少有 2 个场才能使用所有核心。这与https://github.com/subspace/subspace中的默认行为相同[](https://github.com/subspace/subspace)

Can Acres use more CPU by adding multiple farms

**Comment by nazar-pc** [comment]
I literally just said that in the previous comment, yes.

**Comment by zsvvv** [comment]
> 我在之前的评论中确实说过，是的。

I hope to add support for the e5 v3 series CPU. If you use this CPU now, the program will automatically exit. Thank you

**Comment by nazar-pc** [comment]
v3 CPUs are unrelated to support of dual CPUs, please don't mix topics in discussions. V3 CPUs are old, inefficient and not planned to be supported by Space Acres. https://github.com/subspace/subspace and Pulsar support them though.
